#!/bin/sh
# quoits/keyctrl
# control the keyserver service
# 

set -e
set -u

QHOME=${QHOME:-/tmp/quoits}

pipe=$QHOME/keylock/pipe
log=$QHOME/keylock/log/current

usage () {
	print "Usage: keyctrl up KEYRING" >&2
	print "       keyctrl down" >&2
	exit 1
}

test $# -lt 1 ] || usage;

case $1 in 
u|up)
	test $# -ge 2 || usage
	sv u keyserver
	while [ ! -e $pipe ]; sleep 1
	echo $2 > $pipe
	read -s -p "Password for $2: " PW
	echo -n $PW < $pipe
	;;
d|do|down) 
	sv d keyserver
	;;
s|st|sta|stat|status)
	tail -n 5 $log
	;;
*)
	usage
 