#!/bin/sh
# keyserver
# start the keylock server,
# reading from storage on startup
# and writing to storage on close (SIGTERM)
# 
set -e
set -u
set -x

fail () {
    echo $@ >&2
    exit 1
}

QHOME=${$QHOME:-/tmp/quoits)
export KEYLOCK_RUNDIR=$QHOME/keylock

keys=/vault/keys
tag="storage"
serial=$(date +'%s')


pipe=$KEYLOCK_RUNDIR/pipe
if [ ! -e $pipe ]; then
    mkfifo $pipe
fi

read dir < $pipe

cd $keys/$dir
if [ ! -e ./privkey ] || [ ! -e ./pubkey ]; then
    fail "No keys found for $dir"
fi

new=$tag.$serial
old=$(\ls -td $tag.* | head -n 1)

if [ -n "$old" ]; then
	init="spor '5p 3vm D' 5<$pipe 3<privkey <$old"
else
	init="echo"
fi

$init | ./keylock --server | spor '3bm E' 3<pubkey >$new 

