#!/bin/sh
set -e

user=$(basename $(dirname $(pwd)) | sed 's/user-//')
home=/home/$user

cd $home/log || sleep 5 && exit 1

chpst -u $user mkdir -p $home/log/runit

exec 2>&1
exec chpst -u $user /sbin/svlogd $home/log/runit

